services:
  s3app:
    image: prawee/strapi:latest
    container_name: 68-s3-app
    restart: unless-stopped

    env_file:
      - .env

    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: s3db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASS}

    ports:
      - "${APP_PORT}:1337"
